# This is a basic workflow to help you get started with Actions
name: quartoCI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  compile:
    name: compile
    runs-on: ubuntu-latest
    
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Check quarto installation
        run: quarto check
        
      - name: dummy quarto compile
        run: |
          mkdir build docs 
          echo "{{< fa thumbs-up >}} hello from quarto CI" >> docs/index.qmd

      - name: Add FA support and compile
        run: |
          quarto add quarto-ext/fontawesome --no-prompt
          quarto render ../docs/index.qmd
          cp docs/*.html build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # location of the coverage artifacts
          path: "build"

  deploy-coverage:
    runs-on: ubuntu-latest
    needs: compile
    
    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
