# This is a basic workflow to help you get started with Actions
name: quartoCI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  compile:
    name: compile
    runs-on: ubuntu-latest
    steps:
      - name: dummy quarto compile
        run: |
          mkdir docs
          echo "hello from quarto CI" >> docs/index.md

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # location of the coverage artifacts
          path: "docs"

  deploy-coverage:
    runs-on: ubuntu-latest
    needs: compile
    
    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
